In [2]:
#!pip install pandas
#!pip install faker

In [1]:
from faker import Faker
fake = Faker()

lista = []

for i in range(0,10000):
    lista.append({'nombre':fake.name(),'apellido':fake.last_name(),'email':fake.email(),'direccion':fake.address()})

In [2]:
import pandas as pd

In [3]:
data = pd.DataFrame(lista)

In [4]:
data

,nombre,apellido,email,direccion
0,Michael Gonzalez,Johnson,wallstammy@example.com,"4386 Amy Centers Apt. 012\nMauriceburgh, NV 46227"
1,Jeffrey Schmidt,Morris,khanandrew@example.com,"6902 Shawn Islands\nWest Danielle, OR 97763"
2,Sandra Gibson,Snyder,cathy24@example.net,"2851 Kelly Court Apt. 494\nJamesborough, GU 12133"
3,Jonathan Higgins,Trevino,mackenzietran@example.com,"3577 Duran Falls Apt. 808\nNorth Charlestown, ..."
4,Jay Griffin,Cook,daniel09@example.net,"9071 Brown Lodge Suite 093\nSouth Walter, IL 9..."
...,...,...,...,...
9995,Lisa Pena,Meza,georgeirwin@example.net,"692 Ashley Streets\nWest Taylorburgh, WA 47807"
9996,Charles Higgins,Hodges,georgecohen@example.org,"9657 Romero Row Suite 589\nSouth Jim, PA 50193"
9997,James Lamb,Johnson,jared81@example.net,"07455 Shannon Ridges Apt. 182\nRyanmouth, SC 1..."
9998,Sara Morris,Wagner,ericwallace@example.com,"3017 Mark Street\nNorth Ariel, MI 23496"
9999,Amy Guzman,Martinez,hannahortega@example.org,"61698 Schneider Knolls Suite 848\nJeanneland, ..."

In [5]:
import random

data['edad'] = [random.randint(30, 40) for _ in range(len(data))]

In [6]:
data

,nombre,apellido,email,direccion,edad
0,Michael Gonzalez,Johnson,wallstammy@example.com,"4386 Amy Centers Apt. 012\nMauriceburgh, NV 46227",30
1,Jeffrey Schmidt,Morris,khanandrew@example.com,"6902 Shawn Islands\nWest Danielle, OR 97763",40
2,Sandra Gibson,Snyder,cathy24@example.net,"2851 Kelly Court Apt. 494\nJamesborough, GU 12133",32
3,Jonathan Higgins,Trevino,mackenzietran@example.com,"3577 Duran Falls Apt. 808\nNorth Charlestown, ...",30
4,Jay Griffin,Cook,daniel09@example.net,"9071 Brown Lodge Suite 093\nSouth Walter, IL 9...",40
...,...,...,...,...,...
9995,Lisa Pena,Meza,georgeirwin@example.net,"692 Ashley Streets\nWest Taylorburgh, WA 47807",35
9996,Charles Higgins,Hodges,georgecohen@example.org,"9657 Romero Row Suite 589\nSouth Jim, PA 50193",32
9997,James Lamb,Johnson,jared81@example.net,"07455 Shannon Ridges Apt. 182\nRyanmouth, SC 1...",36
9998,Sara Morris,Wagner,ericwallace@example.com,"3017 Mark Street\nNorth Ariel, MI 23496",35
9999,Amy Guzman,Martinez,hannahortega@example.org,"61698 Schneider Knolls Suite 848\nJeanneland, ...",39

In [7]:
provincias = ['Loja', 'Pichincha', 'Guayas', 'Azuay', 'Manabi']

data['provincia'] = [random.choice(provincias) for _ in range(len(data))]

In [8]:
data

,nombre,apellido,email,direccion,edad,provincia
0,Michael Gonzalez,Johnson,wallstammy@example.com,"4386 Amy Centers Apt. 012\nMauriceburgh, NV 46227",30,Guayas
1,Jeffrey Schmidt,Morris,khanandrew@example.com,"6902 Shawn Islands\nWest Danielle, OR 97763",40,Loja
2,Sandra Gibson,Snyder,cathy24@example.net,"2851 Kelly Court Apt. 494\nJamesborough, GU 12133",32,Guayas
3,Jonathan Higgins,Trevino,mackenzietran@example.com,"3577 Duran Falls Apt. 808\nNorth Charlestown, ...",30,Azuay
4,Jay Griffin,Cook,daniel09@example.net,"9071 Brown Lodge Suite 093\nSouth Walter, IL 9...",40,Guayas
...,...,...,...,...,...,...
9995,Lisa Pena,Meza,georgeirwin@example.net,"692 Ashley Streets\nWest Taylorburgh, WA 47807",35,Pichincha
9996,Charles Higgins,Hodges,georgecohen@example.org,"9657 Romero Row Suite 589\nSouth Jim, PA 50193",32,Guayas
9997,James Lamb,Johnson,jared81@example.net,"07455 Shannon Ridges Apt. 182\nRyanmouth, SC 1...",36,Azuay
9998,Sara Morris,Wagner,ericwallace@example.com,"3017 Mark Street\nNorth Ariel, MI 23496",35,Loja
9999,Amy Guzman,Martinez,hannahortega@example.org,"61698 Schneider Knolls Suite 848\nJeanneland, ...",39,Loja

In [9]:
data.to_csv("data_cuaderno1.csv",index=False)